#
# EffectRanks by BryanGaming
# Version: 1.2
#

config:

  prefix: "&a[ERanks] &8|"
  p-variable: "%p"

  error: "&c[Error] &8|"
  e-variable: "%e"

  # Key interact: [NONE /SHIFT/ LEFT-CLICK/ RIGHT-CLICK]
  key: SHIFT
  # Status: power [For permission], group [For groups];
  status: group
  perms:
    reload: effectranks.reload

default:
  cooldown: 30s
  # Displayname [Optional]
  displayname: default
  effects:
  - "speed,50,4"

groups:
  A:
    cooldown: 30s
    displayname: A
    effects:
      - "speed,540,4"

potion:
  # The effect value (%effect-value%) is the loop-value of the effects, if the rank have 2 o more efects:
  # The line with the variable, will multiply depends on the amount of effects placed.
  name: "&fA &a%rank_name% &fpotion."
  format:
    - ""
    - "&aEffects:"
    - "&8- &f%effect-value%"
    - ""
    - "&eClick to use!"
  effect-value: "%name% &8- &f%duration% &8- &f%level%"

time:
  years: years
  year: year
  months: months
  month: month
  weeks: weeks
  week: week
  days: days
  day: day
  hours: hours
  hour: hour
  minutes: minutes
  minute: minute
  seconds: seconds
  second: second